pypy generate_stem.py
pypy generate_unigram.py
pypy generate_bigram.py
pypy generate_distinct_unigram.py
pypy generate_cooccurence_ngram.py
pypy generate_cooccurence_distinct.py
pypy generate_cooccurence_distinct_bigram.py
pypy generate_position_unigram_features.py
pypy generate_position_normalized_unigram_features.py
pypy generate_basic_features.py
pypy generate_basic_features_distinct.py
pypy generate_stop_features.py
pypy generate_idf_dict.py
pypy generate_idf_stats_features.py
pypy generate_hashed.py
pypy generate_hashed_idf.py
pypy generate_hashed_neighbour.py
pypy generate_cooccurence_qid.py
pypy generate_basic_features_minmax.py
pypy generate_basic_features_distinct_minmax.py

pypy generate_mutual_information.py


python generate_tfidf_ngram.py
python generate_tfidf_distinct.py
python generate_tfidf_distinct_bigram.py
python generate_tfidf_coo.py
python generate_tfidf_coo_distinct.py
python generate_len.py
python generate_gensim_sim.py
python generate_selftrained_w2v_sim_dist_diff_idf.py
python generate_pretrained_w2v_sim_dist_diff_idf.py
python generate_tfidf_nmf.py
python generate_hashed_tfidf.py
python generate_tfidf_coo_qid.py
python generate_distinct_word_stats.py
python generate_distinct_word_stats_pretrained.py
python generate_spacy_sim_pretrained.py

python generate_selftrained_glove_sim_dist_diff.py
python generate_tfidf_svd.py
python generate_pattern_mining.py
python generate_sklearn_tfidf_sim.py
python generate_qid_doc.py
python generate_cooccurence_distinct_encoding_by_label.py

python generate_clique_edges_belong_feature.py
python generate_clique_total_feature.py
python generate_fuzz_feature.py
python generate_spacy_entity.py
python generate_ngram_simhash.py
python generate_adjacency_matrix.py
python generate_lda_feature.py

python generate_selftrained_w2v.py


python generate_clique_edges_stats_sep_feature.py
python generate_average_neighbour_degree.py
python generate_graph_subgraph.py

python generate_pretrained_glove_sim_dist_diff_idf.py 
python generate_distinct_word_stats_pretrained_glove.py
python generate_distinct_word_stats_selftrained_glove.py


python generate_distinct_wordnet_stats.py
pypy generate_entropy.py
pypy generate_distinct_entropy.py


python generate_keyword_subgraph.py
python generate_keyword_clique.py


python mf_dense_3_classification.py
python mf_dense_classification.py
python mf_dense_random.py
python mf_dense_regression.py
python mf_dense_weighted_classification.py

python mf_lstm_att_siamese.py
python mf_lstm_classification.py
python mf_lstm_end2end.py
python mf_tfidf_classification.py
